### ISSUE TITLE
Feature: Add buttons for common phrases

### ISSUE THREAD

**Issue by vatbub** [Danesprite/tts-util-app#12]
Because of an accident that I had recently, I am unable to speak for the next few weeks and I started using this app as a tool for communication. I like that the app is simple and clutter free, but I would suggest one addition and that is to give the user the possibility to save common phrases like "Yes" or "I'm ok with that" and have multiple buttons below the `EditText` for quick access to those phrases.

Cheers :)

**Comment by Danesprite** [comment]
Hello Frederik,

My apologies for taking so long to respond to this.  I'm glad to hear that you have found my *TTS Util* app useful.

Thanks to the efforts of @woheller69, the next version of the app will have four memory buttons in the 'Read text' screen.  These can be used to save and quickly retrieve common phrases.  You can see what it will look like [here](https://github.com/Danesprite/tts-util-app/pull/14#issuecomment-947451839).  It would not be difficult to add more buttons in the future, if that is desirable.

The ability to generate wave files from input text (issue #15) will also, once it is implemented, make this easier.

**Comment by Danesprite** [comment]
This feature is now available in version 3.0.0 of the application.  Do please let me know if four buttons is insufficient, it would be trivial to increase the number.

**Comment by vatbub** [comment]
Hey, thanks for implementing the feedback 😎
I just tested it and it seems to work fine, however, since I am able to speak again, I am no longer daily driving the app. Hence, somebody else needs to test the daily usefulness 😎
Cheers and thanks again for your help 😎

**Comment by Danesprite** [comment]
Hello again,

You're very welcome.  Thank you for taking the time to test this new
feature.  I may add two extra buttons in the next version; four doesn't
seem like enough to me.
