### ISSUE TITLE
Utility crashes at the last moment when exporting a text file >~90kB

### ISSUE THREAD

**Issue by gorentolga** [Danesprite/tts-util-app#13]
Hello, just what the title says. I tested it on a Samsung tablet as well as various AVD, it is 100% reproducible for a given file but I don't know if there's a limit on the file size or spoken length or what. For files above ~90-100kB, as soon as the text to speech conversion is 99% in the bar, the TTS Util app crashes and no file is saved.

**Comment by gorentolga** [comment]
A friend helped me to profile the problem, it seems the wave files are joined in memory before saving, and heap memory runs out.
Two solutions: 1) adding android:largeHeap="true" to  <application> tag  increases the heap size somewhat; 2) better is to join the wave files on file instead of in memory:


fun joinWaveFiles(inFiles: List<File>, outFile: File) {
    // Handle special case: empty list.
    if (inFiles.isEmpty()) return
    // Handle special case: single input file.
    // This also handles single non-wave input files.
    if (inFiles.size == 1) {
        outFile.writeBytes(inFiles.first().readBytes())
        return
    }

    // Calculate the SubChunk2Size and ChunkSize.
    var subChunk2Size = 0
    var firstWaveFile: WaveFile? = null
    for (file in inFiles) {
        // Read the wave file.
        // Errors will be thrown if the file is NOT a wave sound file as defined by
        // the following specification: http://soundfile.sapp.org/doc/WaveFormat/
        val waveFile = FileInputStream(file).use { WaveFile(it) }
        // Calculate the SubChunk2Size.
        subChunk2Size += waveFile.subChunk2Size
        if (firstWaveFile != null) {
            if (!waveFile.compatibleWith(firstWaveFile)) {
                throw IncompatibleWaveFileException("wave files with " +
                        "incompatible headers are not supported: " +
                        "$waveFile ~ $firstWaveFile")
            }
        } else {
            firstWaveFile = waveFile
        }

    }

    // Construct a new wave file using header data.
    // Use the first wave file for fields with the same values.
    // Calculate the ChunkSize.
    val chunkSize = 4 + 8 + firstWaveFile!!.subChunk1Size + 8 + subChunk2Size

    // Open the output file for writing.
    FileOutputStream(outFile).use { writeIt ->
        // Write the RIFF header.
        writeIt.write(firstWaveFile.getRiffHeader(chunkSize))

        // Write sub-chunk 1 ("fmt ").
        writeIt.write(firstWaveFile.getSubChunk1())

        // Begin writing sub-chunk 2 ("data").
        writeIt.write(firstWaveFile.bSubChunk2Id)
        writeIt.write(ByteBuffer.allocate(4).putInt(subChunk2Size).array())

        // Write sound data from each file.
        for (file in inFiles) {
            // Read the wave file and write it to the new file.
            val waveFile = FileInputStream(file).use { WaveFile(it) }
            writeIt.write(waveFile.soundData)
        }
    }
}

**Comment by Danesprite** [comment]
I have rewritten this part of the codebase to be more efficient.  I have not published the code yet because it needs further refinement.  (I had forgotten about Android's background process limitations.) This problem will be fixed in the next version.
