### ISSUE TITLE
Text limit constraint and other thoughts

### ISSUE THREAD

**Issue by KevinSJ** [Danesprite/tts-util-app#22]
Hello Danesprite
I really like this app and thanks for creating it and make it open source! 

I had personally tried to creat a similar (toy) app that does similar stuff. Instead of using the share action. I opted to use the text action (my use case is use the app to read long articles), so I can select all text (in reader mode in firefox) and then click on the read to have the article read to me.

Due to nature of most of the articles, I found the built-in text limit for android tts too low for most of them, therefore I used a splitter to split long text (by new line) to work around that limit.

Just wondering, would you accept pull request that
1. work around the text to speech limit like I described above?
2. add a text action that is similar to sharing but one less click? :smile:

**Comment by Danesprite** [comment]
Hello Kevin,

You're welcome, glad you like it.

Using the text action for this is a good idea.  That and the share action
should be able to coexist, I think.  I would welcome a pull request from
you on that; I also have found the additional share menu click to be a
minor annoyance.

Regarding the built-in text limit, (I think it is 5000 characters,) I must
tell you that TTS Util already splits long lines as you suggest.  I came
across the limitation the same way as you, actually.  Do please let me know
if some part of the app is not reading long text correctly.

**Comment by KevinSJ** [comment]
Hello Danesprite,

Will create a PR for text action soon.

Regarding the limit on length, after going through the code, I did realize that you had done it. Sorry for the misunderstanding.

I encountered several cases where the app stop speaking during a long Chinese article which is why I initially thought the functionality is not implemented. Based on my understanding, tts-util converts text to byte array and the spliting is done afterwards, which might be the cause as Chinese characters takes 3 bytes (and my toy app which just naively spliting long string seems to work fine). Will play around more and see if I can find anything.

**Comment by KevinSJ** [comment]
> Hello Danesprite,
> 
> Will create a PR for text action soon.
> 
> Regarding the limit on length, after going through the code, I did realize that you had done it. Sorry for the misunderstanding.
> 
> I encountered several cases where the app stop speaking during a long Chinese article which is why I initially thought the functionality is not implemented. Based on my understanding, tts-util converts text to byte array and the spliting is done afterwards, which might be the cause as Chinese characters takes 3 bytes (and my toy app which just naively spliting long string seems to work fine). Will play around more and see if I can find anything.

actually it looks like this is an issue I c, I had changed the code to add text action and reading long article from there seem to have caused the issue.

**Comment by Danesprite** [comment]
Hello Kevin,

Thank you for submitting the pull request for this feature.  I have not yet
tested your changes, but they look good to me.

Thanks also for explaining the trouble you had with long text input.  No
need to apologise for the misunderstanding.  I have noticed that application
sometimes stops speaking part of the way through when certain text-to-speech
engines are used.  This may be the issue you encountered.  Unfortunately,
there is not much we can do about that particular problem.

I wasn't aware that Chinese characters took three bytes.  I suppose that
might differ depending on the encoding used.  I should say that, although
the string to byte array conversion turned out to be unrelated, any other
method for reading a string as an input stream may be used instead.  Indeed
that would be preferable for longer inputs.

**Comment by KevinSJ** [comment]
Hello Dane,

The PR I created actually have some issues, I used Theme.NoDisplay as theme, trying to hide the interface, this seems to cause the app to force close in some situations. I had switched to use another theme, but will need some time to test it. Will push the update later.

Regarding the long text input issue, it seems to be a bit inconsistent, it was able to speak for 30 minutes continuously without issue yesterday. Now I suspect it might have something to do with battery optimization on my phone.

**Comment by Danesprite** [comment]
Hello Kevin,

I have now tested your PR.  It works quite well.  Reading text this way is
certainly easier than sharing.

I was able to replicate the issue you mentioned with the new activity and
Theme.NoDisplay.  It occurs when the activity is the first one initialised
by the application.  The error only occurs for me when the activity
doesn't immediately finish (in the onCreate() method).  It seems that the
*AppCompatActivity* class may not be used with this theme.

This particular problem may be resolved by using Theme.AppCompat.DayNight
(or some other AppCompat theme) instead.  This will leave the interface
visible in the case mentioned above.  Ideally, the *Activity* class would
be used instead.  I'll see if I can fix that at a later date.

I think you may be right about battery optimisation causing that problem.
The application could also handle background tasks a little better than it
does.

**Comment by KevinSJ** [comment]
Hello Dane,

I have pushed a fix that reverted to use the AppCompact theme for now.

**Comment by Danesprite** [comment]
Thanks again for implementing this useful feature.

Regarding the issue of text-to-speech output occasionally stopping, I'll
try to improve the application's handling of background processing at some
point.
