### ISSUE TITLE
No TTS engine found despite engine(s) working with other apps

### ISSUE THREAD

**Issue by tonykakuuu** [Danesprite/tts-util-app#27]
Device: OnePlus 8T (kebab)
OS: LineageOS 18.1, Android 11 with no GooglePlay Services installed

I installed version 4.0.0 via F-Droid. When I click the top right button to initialize, the message first says "initializing text-to-speech" and then "No text-to-speech engine available". Furthermore, when I navigate to the app settings and and click on TTS Engine (first item from the top) I get a dialogue box which says "Select the TTS engine." but doesn't show any items.   

The problem is that I have installed both RHVoice and eSpeak. Both engines can be selected in the system settings and at least RHVoice is working inside osmAnd, Librera and FitoTrack. TTS Util seems to be the only app that displays this type of behavior.

**Comment by Danesprite** [comment]
Hello Tony,

Thank you for reporting this error.  I am able to reproduce it on Android
11.  Strangely, it does not occur on other versions of Android, e.g. 12.

This will be fixed in the next version of TTS Util.  In the meantime, I
would suggest downgrading to version 3.0.0, which, for whatever reason,
does not have this problem.  You can do this in the F-Droid app.

**Comment by tonykakuuu** [comment]
Just tried downgrading to 3.0.0 and it works now, I can select the engine as expected. 
Thanks!

**Comment by Danesprite** [comment]
No problem, glad I could help.

I have come up with a fix and will release a new version soon.  Until then, I'll leave this issue open; other Android 11 users will have the same trouble.

**Comment by Danesprite** [comment]
This problem is now fixed in *TTS Util* version 4.0.1, which is available from the [releases page](https://github.com/Danesprite/tts-util-app/releases).  It will probably be a few days before this version is available on the F-Droid store.

**Comment by Pantyhose-X** [comment]
> Device: OnePlus 8T (kebab) OS: LineageOS 18.1, Android 11 with no GooglePlay Services installed
> 
> I installed version 4.0.0 via F-Droid. When I click the top right button to initialize, the message first says "initializing text-to-speech" and then "No text-to-speech engine available". Furthermore, when I navigate to the app settings and and click on TTS Engine (first item from the top) I get a dialogue box which says "Select the TTS engine." but doesn't show any items.
> 
> The problem is that I have installed both RHVoice and eSpeak. Both engines can be selected in the system settings and at least RHVoice is working inside osmAnd, Librera and FitoTrack. TTS Util seems to be the only app that displays this type of behavior.

RHVoice and eSpeak Very bad application, their sound listening is completely mechanical.  I suggest you use  "Smart Voice 3.4.0" and [SmartVoice speech synthesizer](https://poretsky.github.io/android/smartvoice/)
Librera Very bad app, can't open big files I suggest you use [legado](https://github.com/gedoor/legado/blob/master/English.md)

**Comment by Danesprite** [comment]
This issue is now resolved in version 4.0.1, now available for download from the Google Play and F-Droid stores.
