### ISSUE TITLE
Problem of system language

### ISSUE THREAD

**Issue by GrimPixel2** [Danesprite/tts-util-app#9]
When the system language is English (United States), open the app, its text-to-speech language is always the same even after changing it in the setting.
When the system language is German (Germany), open the app, it doesn't work, saying “Neither the selected nor the system speaker languages are available”.
Other system languages may also have such problems.

The model is SM-A9200, engine is Google Text-to-speech Engine.

**Comment by Danesprite** [comment]
Thanks for reporting this. I'll see if I can reproduce the issue. Can you please let me know which version of Android you are using and if a German voice is available and downloaded in the Google TTS settings?

Sorry about the late reply.

**Comment by GrimPixel2** [comment]
Sorry, I forgot this account.

It is Android 10. German voice is installed.

**Comment by Danesprite** [comment]
This problem should be resolved in version 3.0.0 of the application (now released).
